name: iris
description: "A modern schedule and work management app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  uuid: ^4.2.2
  path_provider: ^2.1.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 